# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac1014:
      imageName: "macOS-latest"

  maxParallel: 3

pool:
  vmImage: '$(imageName)'

steps:
- task: UsePythonVersion@0
  displayName: Get Python for Python tools.
  inputs:
    versionSpec: '3.7'
  name: pyTools

- bash: |
    python --version
    python -m pip install --upgrade jinja2
    python -m pip install --upgrade setuptools wheel
    python -m pip install --upgrade pip
    python -m pip install --upgrade conan
    conan --version
  displayName: 'Install Conan'

- bash: |
    mkdir build
    pushd build
    conan remote add ot_deps https://api.bintray.com/conan/opentissue/Deps
    conan install .. || exit 1
    popd
  displayName: 'Resolve Dependencies'

- bash: |
    cmake -DOPENTISSUE_ENABLE_UNIT_TESTS=ON -S ${PWD} -B ${PWD}/build
    cmake --build ${PWD}/build --target Continuous -j 2
    pushd build
    ctest -T Test
    popd
  displayName: 'Build and Run Unit Tests'

- bash: |
    cmake -DOPENTISSUE_ENABLE_UNIT_TESTS=OFF -S ${PWD} -B ${PWD}/build
    cmake --build ${PWD}/build --target package
  displayName: 'Package'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: cTest
    testResultsFiles: build/Testing/*/Test.xml
    testRunTitle: 'Publish test results'

- task: CopyFiles@2
  inputs:
    contents: 'build/OpenTissue-*'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
